# Welcome to Jekyll!
#

# Site settings
title: Urgent Announcement
description: |
   We regret to inform you, that due to the restrictions around COVID-19 we are deciding to postpone our wedding.  
   I want to know that we both love you all very much, and that we hope you are staying safe out there.  
   This was a very difficult decision to make, but we realize that we should give our guests as much time as possible 
   to try and rearrange their travel plans.  We do not have a new date, and as soon as we are able to rearrange 
   and reschedule, we will let you know.  In order to get up to date information, please still RSVP using the link
   below and we will give you up to date information.  When a new date is found, we will use the RSVP list to send out
   a new RSVP for the correct date.
   
   Stay Safe,
   
   Safiya and Nick


owner: Nick & Safiya # or company name
first_published: 2019 # if migrating another site, the year of your first publish
email: trowelandkeyboard@gmail.com
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://trowelandkeyboard.net" # the base hostname & protocol for your site
social:
  #twitter: https://twitter.com/<username>
  # github: https://github.com/<username>
  # linkedin-square: https://linkedin.com/in/<username>
  # facebook-official: https://facebook.com/<username>
  # google-plus-square: https://plus.google.com/u/0/+<username>
  # #email: /contact/
  #flickr:
  #instagram:
  #youtube-square:
  #spotify:
  #stack-overflow:
  #vimeo:
  #reddit:
  #stubleupon:
  #delicious:
  #pied-piper:
  #digg:
  #soundcloud:
  #deviantart:
  #angellist:
  #tumblr-square:
  #stackexchange:
  #weibo:
  #trello:
  #foursquare:
  #linux:
  #bitbucket-square:
  #vk:
  #slack:
  #vine:
  #weixin:
  #yelp:
  #skyatlas:
  #leanpub:
  #connectdevelop:
  #ils:
  #forumbee:
  #tripadvisor:
  #amazon:

# Build settings
markdown: kramdown
#sass:
#  style: compressed
